version = 0.1

[default.build.parameters]
template_file = "infrastructure/template.yaml"

[default.deploy.parameters]
template_file = ".aws-sam/build/template.yaml"
stack_name = "cloudpulse"
resolve_s3 = true
s3_prefix = "cloudpulse"
region = "ap-south-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\" AlertEmail=\"admin@example.com\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
