version = 0.1

[default.deploy.parameters]
stack_name = "cloudpulse"
resolve_s3 = true
s3_prefix = "cloudpulse"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" AlertEmail=\"admin@example.com\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
